### ISSUE TITLE
Meshblu with different convencional port crash Meshblukit

### ISSUE THREAD

**Issue by ericbbraga** [octoblu/MeshbluKit-Android#1]
I've created a private Meshblu instance in my computer using the port 3000. When I've tried connect with this instance, using the follow code I've received an error:

Code
SaneJSONObject meshbluConfig = new SaneJSONObject();
// other configurations ...
meshbluConfig.putIntOrIgnore("port", 3000);

Error
**12-02 10:46:55.193 9108-9108/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.asdf.app, PID: 9108
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.asdf.app/com.asdf.app.MainActivity}: java.util.UnknownFormatConversionException: Conversion: i
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
   at android.app.ActivityThread.access$800(ActivityThread.java:151)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5254)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)**

The problem is the String.format in the Meshblu.java class. We don't have the "%i" format, instead we have "%d"

**Comment by peterdemartini** [comment]
If you are up for it, we do accept pull requests. If that isn't option, we can handle it.
